name: rawg_ex ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  OTP-VERSION: 25.2.3
  ELIXIR-VERSION: 1.14.3

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP-VERSION }}
          elixir-version: ${{ env.ELIXIR-VERSION }}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.OTP-VERSION }}-${{ env.ELIXIR-VERSION }}-${{ hashFiles('mix.lock') }}
      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix compile
          mix dialyzer --plt
      - name: Check
        run: |
          mix check
          mix test
